export const ActionTypes = {

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCESS: 'USER_LOGIN_SUCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    // On Page Refresh
    USER_ALLRADY_LOGIN: "USER_ALLRADY_LOGIN",
    // On LogOut 
    LOG_OUT: "LOG_OUT",

    CLEAR_MESSAGE: "CLEAR_MESSAGE",

    GET_ALL_USERS_LIST_REQUEST: 'GET_ALL_USERS_LIST_REQUEST',
    GET_ALL_USERS_LIST_SUCESS: 'GET_ALL_USERS_LIST_SUCESS',
    GET_ALL_USERS_LIST_FAIL: 'GET_ALL_USERS_LIST_FAIL',


};
// BASE URLS
export const BASE_URL = "https://api.storerestapi.com/";

